version: 2.1

job_defaults: &job_defaults
  working_directory: ~/ng-build-monolithic
  docker:
    - image: cimg/node:lts-browsers

orbs:
  node: circleci/node@5.2.0
  build-tools: circleci/build-tools@3.0.0
  browser-tools: circleci/browser-tools@1.5.3

commands:
  checkout_and_rebase:
    description: Checkout and verify clean merge with main branch
    steps:
      - checkout
      - run:
          name: Set git user.name and user.email for rebase.
          # User is required for rebase.
          command: |
            git config user.name "devintent-ci"
            git config user.email "ci@devintent.com"
      - build-tools/merge-with-parent:
          parent: main

  setup:
    description: 'Set up executor'
    steps:
      - attach_workspace:
          at: ~/

jobs:
  initialize:
    <<: *job_defaults
    steps:
      - checkout_and_rebase
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install-packages
      - persist_to_workspace:
          root: ~/
          paths:
            - ng-build-monolithic

  build:
    <<: *job_defaults
    steps:
      - setup
      - run: npm run build

workflows:
  build:
    jobs:
      - initialize
      - build:
          requires:
            - initialize
